# Generated by Django 5.2.1 on 2025-05-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='A unique identifier for the event in the URL.', max_length=200, unique=True)),
                ('about_event', models.TextField()),
                ('main_speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours (e.g., 2.5 for 2 hours 30 mins)', max_digits=5, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_pics')),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to hide event without deleting.')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
